Models/Pedido.cs
using Carrito.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Carrito.Models
{
    public class Pedido
    {
        [Display(Name = "PedidoID")]
        public int PedidoID { get; set; }
        
        [Display(Name = "Autoservicio")]
        public int AutoservicioID { get; set; }
        public Autoservicio Autoservicio { get; set; }

        [Display(Name = "Cliente")]
        public int ClienteID { get; set; }
        public Cliente Cliente { get; set; }

        [Display(Name = "MetodoPago")]
        public int MetodoPagoID { get; set; }
        public MetodoPago MetodoPago { get; set; }

        [Display(Name = "Domicilio")]
        public int DomicilioID { get; set; }
        public Domicilio Domicilio { get; set; }

        public DateTime FechaHora { get; set; }
        public string Direccion { get; set; }
        public int Total { get; set; }


    }
}

Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Carrito.Models;

namespace Carrito.Controllers
{
    public class ClientesController : Controller
    {
        private readonly CarritoContext _context;

        public ClientesController(CarritoContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cliente.ToListAsync());
        }

        public IActionResult IndexCl()
        {
            ViewData["consulta"] = "cliente";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> IndexCl([Bind("ClienteID,Nombre,Apellido,Direccion,Email,Telefono,Documento")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexCl));
            }
            return View(cliente);
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.ClienteID == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClienteID,Nombre,Apellido,Direccion,Email,Telefono,Documento")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClienteID,Nombre,Apellido,Direccion,Email,Telefono,Documento")] Cliente cliente)
        {
            if (id != cliente.ClienteID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ClienteID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.ClienteID == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Cliente.FindAsync(id);
            _context.Cliente.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Cliente.Any(e => e.ClienteID == id);
        }

        public IActionResult listar()
        {
            return View();
        }
        public async Task<IActionResult> listar(string email)
        {
            if (email == null)
            {
                return NotFound();
            }
            var cliente = _context.Cliente
                .Where(m => m.Email == email)
                .Select(m => new
                {
                    nombre=m.Nombre,
                    apellido=m.Apellido,
                    direccion=m.Direccion,
                    email=m.Email
                }).ToList();

            await _context.SaveChangesAsync();
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

    }
}

Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Carrito.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace Carrito.Controllers
{
    public class PedidosController : Controller
    {
        private readonly CarritoContext _context;

        public PedidosController(CarritoContext context)
        {
            _context = context;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            var carritoContext = _context.Pedido.Include(p => p.Autoservicio).Include(p => p.Cliente).Include(p => p.Domicilio).Include(p => p.MetodoPago);
            return View(await carritoContext.ToListAsync());
        }

        

        public IActionResult IndexCl()
        {          
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre");
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre");
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID");
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> IndexCl([Bind("PedidoID,AutoservicioID,ClienteID,MetodoPagoID,DomicilioID,FechaHora,Direccion,Total")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexCl));
            }
            Cliente cliente = new Cliente
            {
                Nombre = pedido.Cliente.Nombre,
                Apellido = pedido.Cliente.Apellido,
                Direccion = pedido.Cliente.Direccion
            };
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = cliente;
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre", pedido.MetodoPagoID);
            return View(cliente);
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido
                .Include(p => p.Autoservicio)
                .Include(p => p.Cliente)
                .Include(p => p.Domicilio)
                .Include(p => p.MetodoPago)
                .FirstOrDefaultAsync(m => m.PedidoID == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre");
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre");
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID");
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoID,AutoservicioID,ClienteID,MetodoPagoID,DomicilioID,FechaHora,Direccion,Total")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = new SelectList(_context.Autoservicio, "ClienteID", "Nombre", pedido.AutoservicioID);
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "Nombre", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "NumeroReferencia", pedido.MetodoPagoID);
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre", pedido.ClienteID);
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre", pedido.MetodoPagoID);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoID,AutoservicioID,ClienteID,MetodoPagoID,DomicilioID,FechaHora,Direccion,Total")] Pedido pedido)
        {
            if (id != pedido.PedidoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre", pedido.ClienteID);
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre", pedido.MetodoPagoID);
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido
                .Include(p => p.Autoservicio)
                .Include(p => p.Cliente)
                .Include(p => p.Domicilio)
                .Include(p => p.MetodoPago)
                .FirstOrDefaultAsync(m => m.PedidoID == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedido.FindAsync(id);
            _context.Pedido.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedido.Any(e => e.PedidoID == id);
        }

        public void SetSession(object obj)
        {
            HttpContext.Session.SetString("carrito", JsonConvert.SerializeObject(obj));
        }

        public string GetSession()
        {
            return HttpContext.Session.GetString("carrito");

        }

        [HttpPost]
        public string Agregar([FromBody] Pedido modelo)
        {
            if (GetSession() == null)
            {
                List<Pedido> lista = new List<Pedido>();
                lista.Add(modelo);
                SetSession(lista);
            }
            else
            {
                List<Pedido> lista = JsonConvert.DeserializeObject<List<Pedido>>(GetSession());
                lista.Add(modelo);
                SetSession(lista);
            }
            var value = GetSession();
            return value;
        }
        [HttpGet]
        public string Llenar()
        {
            var session = GetSession();
            return session;
        }


    }
}

Views/Pedidos/Create.cshtml
@model Carrito.Models.Pedido

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AutoservicioID" class="control-label"></label>
                <select asp-for="AutoservicioID" class ="form-control" asp-items="ViewBag.AutoservicioID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClienteID" class="control-label"></label>
                <select asp-for="ClienteID" class ="form-control" asp-items="ViewBag.ClienteID"></select>
            </div>
            <div class="form-group">
                <label asp-for="MetodoPagoID" class="control-label"></label>
                <select asp-for="MetodoPagoID" class ="form-control" asp-items="ViewBag.MetodoPagoID"></select>
            </div>
            <div class="form-group">
                <label asp-for="DomicilioID" class="control-label"></label>
                <select asp-for="DomicilioID" class ="form-control" asp-items="ViewBag.DomicilioID"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaHora" class="control-label"></label>
                <input asp-for="FechaHora" class="form-control" />
                <span asp-validation-for="FechaHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pedidos/Delete.cshtml
@model Carrito.Models.Pedido

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autoservicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Autoservicio.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cliente.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MetodoPago)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MetodoPago.NumeroReferencia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Domicilio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Domicilio.DomicilioID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaHora)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaHora)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PedidoID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Pedidos/Details.cshtml
@model Carrito.Models.Pedido

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autoservicio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Autoservicio.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cliente.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MetodoPago)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MetodoPago.NumeroReferencia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Domicilio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Domicilio.DomicilioID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaHora)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaHora)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PedidoID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Pedidos/Edit.cshtml
@model Carrito.Models.Pedido

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PedidoID" />
            <div class="form-group">
                <label asp-for="AutoservicioID" class="control-label"></label>
                <select asp-for="AutoservicioID" class="form-control" asp-items="ViewBag.AutoservicioID"></select>
                <span asp-validation-for="AutoservicioID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClienteID" class="control-label"></label>
                <select asp-for="ClienteID" class="form-control" asp-items="ViewBag.ClienteID"></select>
                <span asp-validation-for="ClienteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetodoPagoID" class="control-label"></label>
                <select asp-for="MetodoPagoID" class="form-control" asp-items="ViewBag.MetodoPagoID"></select>
                <span asp-validation-for="MetodoPagoID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DomicilioID" class="control-label"></label>
                <select asp-for="DomicilioID" class="form-control" asp-items="ViewBag.DomicilioID"></select>
                <span asp-validation-for="DomicilioID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaHora" class="control-label"></label>
                <input asp-for="FechaHora" class="form-control" />
                <span asp-validation-for="FechaHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pedidos/Index.cshtml
@model IEnumerable<Carrito.Models.Pedido>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a class="btn btn-outline-success" title="Nuevo articulo" asp-action="Create"><i class="fas fa-cart-plus"></i></a>
</p>
<table class="table table-hover table-striped table-dark">
    <thead class="text-center text-warning">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Autoservicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MetodoPago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Domicilio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Autoservicio.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MetodoPago.NumeroReferencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Domicilio.DomicilioID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaHora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.PedidoID"><i class="fas fa-box-open"></i></a>
                <a class="btn btn-outline-secondary" asp-action="Details" asp-route-id="@item.PedidoID"><i class="fas fa-info"></i></a>
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.PedidoID"><i class="fas fa-cart-arrow-down"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a class="btn btn-warning" asp-controller="Home" asp-action="Admin"><i class="fas fa-backspace"></i></a>
</div>

Views/Pedidos/IndexCl.cshtml
@model Carrito.Models.Pedido

@{
    ViewData["Title"] = "IndexCl";
}

<h2>IndexCl</h2>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="IndexCl">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AutoservicioID" class="control-label"></label>
                <select asp-for="AutoservicioID" class="form-control" asp-items="ViewBag.AutoservicioID"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClienteID" class="control-label"></label>
                <select asp-for="ClienteID" class="form-control" asp-items="ViewBag.ClienteID"></select>
            </div>
            <div class="form-group">
                <label asp-for="MetodoPagoID" class="control-label"></label>
                <select asp-for="MetodoPagoID" class="form-control" asp-items="ViewBag.MetodoPagoID"></select>
            </div>
            <div class="form-group">
                <label asp-for="DomicilioID" class="control-label"></label>
                <select asp-for="DomicilioID" class="form-control" asp-items="ViewBag.DomicilioID"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaHora" class="control-label"></label>
                <input asp-for="FechaHora" class="form-control" />
                <span asp-validation-for="FechaHora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </form>
    </div>
    <div class="card text-left">

        <div class="card-footer cFoo text-muted">
            <nav class="navIt" aria-label="...">
                <ul class="pagination pagination-lg">
                    <li class="">
                        <a class="page-link bg-warning text-dark shadow" asp-controller="Articulos" asp-action="Index"><i class="fas fa-shopping-basket"></i></a>
                    </li>
                    <li class="page-item " aria-current="page">
                        <a class="page-link shadow" asp-controller="DetallePedidos" asp-action="Index"><i class="fas fa-cart-plus"></i></a>
                    </li>
                    <li class="page-item"><a class="page-link" asp-controller="Clientes" asp-action="IndexCl"><i class="fas fa-user-tag shadow"></i></a></li>
                    <li class="page-item">
                        <span class="page-link border-0">
                            <a class="page-link" asp-controller="Pedidos" asp-action="IndexCl"><i class="fas fa-dolly shadow-lg"></i></a>
                        </span>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}