Models/DetallePedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Carrito.Models
{
    public class DetallePedido
    {
        public int DetallePedidoID { get; set; }
        public Articulo Articulo { get; set; }
        public decimal Cantidad { get; set; }
        private decimal _Total;

        public decimal Total
        {
            get
            {
                _Total = (Articulo.Precio * Cantidad);
                return _Total;
            }
            set
            {
                _Total = value;
            }
        }
        public decimal PrecioTotal { get; set; }
    }
}

Controllers/DetallePedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Carrito.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace Carrito.Controllers
{
    public class DetallePedidosController : Controller
    {
        private readonly CarritoContext _context;

        public DetallePedidosController(CarritoContext context)
        {
            _context = context;
        }

        // GET: DetallePedidos
        public async Task<IActionResult> Index()
        {
            return View(await _context.DetallePedido.ToListAsync());
        }
        public async Task<IActionResult> Siguiente()
        {
            return View(await _context.DetallePedido.ToListAsync());
        }
        public async Task<IActionResult> Edit()
        {
            return View(await _context.DetallePedido.ToListAsync());
        }


        public void SetSession(object obj)
        {
            HttpContext.Session.SetString("carrito", JsonConvert.SerializeObject(obj));
        }

        public string GetSession()
        {
            return HttpContext.Session.GetString("carrito");

        }

        [HttpPost]
        public string Agregar([FromBody] DetallePedido modelo)
        {
            if (GetSession() == null)
            {
                List<DetallePedido> lista = new List<DetallePedido>();
                lista.Add(modelo);
                SetSession(lista);
            }
            else
            {
                List<DetallePedido> lista = JsonConvert.DeserializeObject<List<DetallePedido>>(GetSession());
                lista.Add(modelo);
                SetSession(lista);
            }
            var value = GetSession();
            return value;
        }
        [HttpGet]
        public string Llenar()
        {
            var session = GetSession();
            return session;
        }

        [HttpPost]
        public void Editar([FromBody] DetallePedido modelo)
        {
            List<DetallePedido> lista = JsonConvert.DeserializeObject<List<DetallePedido>>(GetSession());
            var resultado = lista.FirstOrDefault(p => p.Articulo.ArticuloID == modelo.Articulo.ArticuloID);
            if (resultado != null)
            {
                resultado.Cantidad = modelo.Cantidad;
                resultado.Total = modelo.Total;
                resultado.PrecioTotal = modelo.PrecioTotal;
            }
            SetSession(lista);
        }
        [HttpPost]
        public string Eliminar(int articuloID)
        {
            List<DetallePedido> lista = JsonConvert.DeserializeObject<List<DetallePedido>>(GetSession());
            lista.RemoveAll(p => p.Articulo.ArticuloID == articuloID);
            SetSession(lista);
            var value = GetSession();
            return value;
        }
    }
}

Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Carrito.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace Carrito.Controllers
{
    public class PedidosController : Controller
    {
        private readonly CarritoContext _context;

        public PedidosController(CarritoContext context)
        {
            _context = context;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            var carritoContext = _context.Pedido.Include(p => p.Autoservicio).Include(p => p.Cliente).Include(p => p.Domicilio).Include(p => p.MetodoPago);
            return View(await carritoContext.ToListAsync());
        }

        

        public IActionResult IndexCl()
        {          
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre");
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre");
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID");
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> IndexCl([Bind("PedidoID,AutoservicioID,ClienteID,MetodoPagoID,DomicilioID,FechaHora,Direccion,Total")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(IndexCl));
            }
            Cliente cliente = new Cliente
            {
                Nombre = pedido.Cliente.Nombre,
                Apellido = pedido.Cliente.Apellido,
                Direccion = pedido.Cliente.Direccion
            };
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = cliente;
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre", pedido.MetodoPagoID);
            return View(cliente);
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido
                .Include(p => p.Autoservicio)
                .Include(p => p.Cliente)
                .Include(p => p.Domicilio)
                .Include(p => p.MetodoPago)
                .FirstOrDefaultAsync(m => m.PedidoID == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre");
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre");
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID");
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoID,AutoservicioID,ClienteID,MetodoPagoID,DomicilioID,FechaHora,Direccion,Total")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = new SelectList(_context.Autoservicio, "ClienteID", "Nombre", pedido.AutoservicioID);
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "Nombre", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "NumeroReferencia", pedido.MetodoPagoID);
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre", pedido.ClienteID);
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre", pedido.MetodoPagoID);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoID,AutoservicioID,ClienteID,MetodoPagoID,DomicilioID,FechaHora,Direccion,Total")] Pedido pedido)
        {
            if (id != pedido.PedidoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutoservicioID"] = new SelectList(_context.Autoservicio, "AutoservicioID", "Nombre", pedido.AutoservicioID);
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nombre", pedido.ClienteID);
            ViewData["DomicilioID"] = new SelectList(_context.Domicilio, "DomicilioID", "DomicilioID", pedido.DomicilioID);
            ViewData["MetodoPagoID"] = new SelectList(_context.MetodoPago, "MetodoPagoID", "Nombre", pedido.MetodoPagoID);
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido
                .Include(p => p.Autoservicio)
                .Include(p => p.Cliente)
                .Include(p => p.Domicilio)
                .Include(p => p.MetodoPago)
                .FirstOrDefaultAsync(m => m.PedidoID == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedido.FindAsync(id);
            _context.Pedido.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedido.Any(e => e.PedidoID == id);
        }

        public void SetSession(object obj)
        {
            HttpContext.Session.SetString("carrito", JsonConvert.SerializeObject(obj));
        }

        public string GetSession()
        {
            return HttpContext.Session.GetString("carrito");

        }

        [HttpPost]
        public string Agregar([FromBody] Pedido modelo)
        {
            if (GetSession() == null)
            {
                List<Pedido> lista = new List<Pedido>();
                lista.Add(modelo);
                SetSession(lista);
            }
            else
            {
                List<Pedido> lista = JsonConvert.DeserializeObject<List<Pedido>>(GetSession());
                lista.Add(modelo);
                SetSession(lista);
            }
            var value = GetSession();
            return value;
        }
        [HttpGet]
        public string Llenar()
        {
            var session = GetSession();
            return session;
        }


    }
}

Views/DetallePedidos/Create.cshtml
@model Carrito.Models.DetallePedido

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>DetallePedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioTotal" class="control-label"></label>
                <input asp-for="PrecioTotal" class="form-control" />
                <span asp-validation-for="PrecioTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DetallePedidos/Delete.cshtml
@model Carrito.Models.DetallePedido

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DetallePedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrecioTotal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DetallePedidoID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/DetallePedidos/Details.cshtml
@model Carrito.Models.DetallePedido

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>DetallePedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PrecioTotal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DetallePedidoID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/DetallePedidos/Edit.cshtml
@model Carrito.Models.DetallePedido

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>DetallePedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DetallePedidoID" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioTotal" class="control-label"></label>
                <input asp-for="PrecioTotal" class="form-control" />
                <span asp-validation-for="PrecioTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DetallePedidos/Index.cshtml
@model IEnumerable<DetallePedido>

@{
    ViewData["Title"] = "Index";
}
<br />
<br />

    <div class="container">
        <table class="table table-hover table-striped table-dark">
            <thead>
                <tr class="font-weight-bolder">
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="tbodyDetallePedido"></tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="text-right">PrecioTotal</td>
                    <td><label id="lblTotal"></label></td>

                </tr>

            </tfoot>

        </table>
    </div>
    <div class="cFoo">
        <nav aria-label="...">
            <ul class="pagination pagination-lg">
                <li class="page-item " aria-current="page">
                    <span class="page-link">
                        <a class="page-link" asp-controller="DetallePedidos" asp-action="Index"><i class="fas fa-cart-plus"></i></a>
                    </span>
                </li>
                <li class="page-item"><a class="page-link" asp-controller="Clientes" asp-action="IndexCl"><i class="fas fa-user-tag"></i></a></li>
                <li class="page-item"><a class="page-link" asp-controller="Pedidos" asp-action="IndexCl"><i class="fas fa-dolly"></i></a></li>
            </ul>
        </nav>
    </div>

<div class="modal fade" id="modalEditar">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Editar 2</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ArticuloId:<label id="lblId"></label><br />
                Nombre:<label id="lblNombre"></label><br />
                Precio:<label id="lblPrecio"></label><br />
                Cantidad: <input type="text" id="txtEditarCtd" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="btnEditar" class="btn btn-primary">Editar</button>
            </div>
        </div>
    </div>
</div>



<script>
    $(function () {
        fnLlenar();
        fnEditar();
        fnEditarBtn();
        fnEliminar();
    });

    function fnLlenar() {
        var tbody = "";
        $.ajax({
            type: "GET",
            url: "DetallePedidos/Llenar",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {

                if (typeof data != "undefined") {
                    for (var i = 0; i < data.length; i++) {
                        tbody = "<tr>";
                        tbody += "<td>" + data[i].Articulo.ArticuloID + "</td>";
                        tbody += "<td>" + data[i].Articulo.Nombre + "</td>";
                        tbody += "<td>" + data[i].Articulo.Precio + "</td>";
                        tbody += "<td>" + data[i].Cantidad + "</td>";
                        tbody += "<td>" + data[i].Total + "</td>";
                        tbody += "<td>";
                        tbody += "<input type='button' id='btnEditar' value='Editar' class='btn btn-outline-warning'/>" ;
                        tbody += "<input type='button' id='btnEliminar' value='Eliminar' class='btn btn-outline-danger'/>" ;
                        tbody += "</td>";
                        tbody += "</tr>";
                        $("#tbodyDetallePedido").append(tbody);
                        fnPrecioTotal();
                    }
                    console.log(data);
                }
            },




            error: function () {

            }

        });
    }
    function fnPrecioTotal() {
        var sumaTotal = 0;
        $("#tbodyDetallePedido").find("tr").each(function () {
            var total = parseFloat($(this).find("td").eq(4).text())
            sumaTotal += total;
        });
        $("#lblTotal").text(sumaTotal);
    }

    var col_ArticuloID;
    var col_nombre;
    var col_precio;
    var col_cantidad;
    var col_total;
    var popup;
    function fnEditar() {
        $(document).on("click", "#btnEditar", function () {
            popup = $("#modalEditar");
            col_ArticuloID = $(this).closest("tr").find("td").eq(0).text();
            col_nombre = $(this).closest("tr").find("td").eq(1).text();
            col_precio = $(this).closest("tr").find("td").eq(2);
            col_cantidad = $(this).closest("tr").find("td").eq(3);
            col_total = $(this).closest("tr").find("td").eq(4);

            popup.find("#lblId").text(col_ArticuloID);
            popup.find("#lblNombre").text(col_nombre);
            popup.find("#lblPrecio").text(col_precio.text());
            popup.find("#txtEditarCtd").val(col_cantidad.text());
            popup.modal();
        });
    }

    function fnEditarBtn() {
        $("#btnEditar").on("click", function () {
            col_cantidad.text($("#txtEditarCtd").val());

            var monto = parseFloat(col_precio.text() * col_cantidad.text());
            col_total.text(monto);
            fnPrecioTotal();

            popup.modal("hide");

            var odata = {
                "Articulo": {
                    "ArticuloID": col_ArticuloID,
                },
                "Cantidad": col_cantidad.text(),
                "Total": $("#lblTotal").text()
            };
            console.log(odata);

            $.ajax({
                type: "POST",
                url: "DetallePedidos/Editar",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify(odata),
                success: function (d) {
                    console.log(d);
                },
                error: function () {

                }
            });
        });
    }
    function fnEliminar() {
        $(document).on("click", "#btnEliminar", function () {

            var idArticulo = $(this).closest("tr").find("td").eq(0).text();
            $.ajax({
                type: "POST",
                url: "DetallePedidos/Eliminar/?articuloID=" + idArticulo,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (d) {
                    if (d != null || d != "") {
                        fnPrecioTotal();
                    }
                },
                error: function () {

                }
            });
            $(this).closest("tr").remove();
        });
    }
</script>

Views/DetallePedidos/Siguiente.cshtml
@model Carrito.Models.DetallePedido

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>DetallePedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DetallePedidoID" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioTotal" class="control-label"></label>
                <input asp-for="PrecioTotal" class="form-control" />
                <span asp-validation-for="PrecioTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}