Models/Empleado.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Carrito.Models
{
    public class Empleado
    {
        public int EmpleadoID { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Los nombres tiene que tener de minimo 3" +
            "a 50 caracteres")]
        public string Nombre { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Los apellidos tiene que tener de minimo 3" +
            "a 50 caracteres")]
        public string Apellido { get; set; }
        [Required]
        public string Documento { get; set; }
        [Required]
        public string Cargo { get; set; }
        [Required]
        public string Telefono { get; set; }
        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            public int InputModelID { get; set; }
            
            [Required]
            [EmailAddress]
            public string Email { get; set; }
            [Required]
            [DataType(DataType.Password)]
            public string Contraseña { get; set; }
        }
    }
}

Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Carrito.Models;

namespace Carrito.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly CarritoContext _context;

        public EmpleadosController(CarritoContext context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index()
        {
            return View(await _context.Empleado.ToListAsync());
        }

        public async Task<IActionResult> IndexCl()
        {
            return View(await _context.Empleado.ToListAsync());
        }

        public IActionResult Login()
        {
            return View();
        }

        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .FirstOrDefaultAsync(m => m.EmpleadoID == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmpleadoID,Nombre,Apellido,Documento,Cargo,Telefono")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmpleadoID,Nombre,Apellido,Documento,Cargo,Telefono")] Empleado empleado)
        {
            if (id != empleado.EmpleadoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.EmpleadoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleado
                .FirstOrDefaultAsync(m => m.EmpleadoID == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleado.FindAsync(id);
            _context.Empleado.Remove(empleado);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleado.Any(e => e.EmpleadoID == id);
        }
    }
}

Views/Empleados/Create.cshtml
@model Carrito.Models.Empleado

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.Email" class="control-label"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.Contraseña" class="control-label"></label>
                <input asp-for="Input.Contraseña" class="form-control" />
                <span asp-validation-for="Input.Contraseña" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Empleados/Delete.cshtml
@model Carrito.Models.Empleado

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Documento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Documento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EmpleadoID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Empleados/Details.cshtml
@model Carrito.Models.Empleado

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Documento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Documento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EmpleadoID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Empleados/Edit.cshtml
@model Carrito.Models.Empleado

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmpleadoID" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Empleados/Index.cshtml
@model IEnumerable<Carrito.Models.Empleado>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a class="btn btn-outline-success" title="Nuevo articulo" asp-action="Create"><i class="fas fa-cart-plus"></i></a>
</p>
<table class="table table-hover table-striped table-dark">
    <thead class="text-center text-warning">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cargo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Input.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Input.Contraseña)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Input.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Input.Contraseña)
            </td>
            <td>
                <a class="btn btn-outline-warning"asp-action="Edit" asp-route-id="@item.EmpleadoID"><i class="fas fa-box-open"></i></a>
                <a class="btn btn-outline-secondary" asp-action="Details" asp-route-id="@item.EmpleadoID"><i class="fas fa-info"></i></a>
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.EmpleadoID"><i class="fas fa-cart-arrow-down"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a class="btn btn-warning" asp-controller="Home" asp-action="Admin"><i class="fas fa-backspace"></i></a>
</div>

Views/Empleados/IndexCL.cshtml
@model  Empleado
@{
    ViewData["Title"] = "IndexCL";
}

<h2>IndexCL</h2>

<div>
    <form asp-controller="Empleados" asp-action="IndexCl" method="post">
        <h1>Hi</h1>
        <div asp-validation-summary="All"></div>
        <div class="form-group">
            <label asp-for="Input.Email" class="control-label"></label>
            <input asp-for="Input.Email" class="form-control" />
            <span asp-validation-for="Input.Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Input.Contraseña" class="control-label"></label>
            <input asp-for="Input.Contraseña" class="form-control" />
            <span asp-validation-for="Input.Contraseña" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn">Iniciar</button>
        </div>
    </form>
</div>

Views/Empleados/Login.cshtml
@model Empleado
@{
    ViewData["Title"] = "Login";
}<br />
<br />
    <div class="card border-dark mb-3" style="width: 35rem;margin:auto;">
        <div class="card-body text-dark">
            <form>
                <div class="form-group">
                     <label asp-for="Input.Email" for="Email"><h5><i class="fas fa-users-cog"></i> &nbsp;Correo electronico</h5></label>
                    <input asp-for="Input.Email" type="email" class="form-control" id="Email" aria-describedby="emailHelp" placeholder="Ingrese correo electronico">
                    
                </div>
                <div class="form-group">
                    <label asp-for="Input.Contraseña" for="Password"><h5><i class="fas fa-unlock-alt"></i> &nbsp;Contraseña</h5></label>
                    <input asp-for="Input.Contraseña" type="password" class="form-control" id="Password" placeholder="Ingrese su contraseña">
                </div>
                <button type="submit" class="btn btn-outline-dark" asp-controller="Home" asp-action="Admin">Ingresar</button>
                <div class="alert alert-warning" role="alert">
                    <p id="alert"></p>
                </div>
            </form>
        </div>
    </div>
<script>
    
</script>